### ISSUE TITLE
parse_url() expects parameter 1 to be string

### ISSUE THREAD

**Issue by xiaoxing598** [centraldesktop/php-stomp#14]
The following error occurred

```
PHP Warning:  parse_url() expects parameter 1 to be string, array given in \vendor\centraldesktop\st
omp\src\CentralDesktop\Stomp\Connection.php on line 131

```

This is the wrong location

```
$brokerUri = $hostIterator->current();
// I hate that PHP doens't have a URL/URI object
$url = parse_url($brokerUri);
```

The cause of the error was due to $ brokerUrl is not a string, so it should not be resolved, it is an array, which when connected to a good distribution of.

```
Failover(array(array('host1',61612) ,array('host2',61612)), true);
```

**Comment by dstevenson** [comment]
You should be constructing your `ConnectionFactory` with just an array of host URLs, not an array of arrays.

E.g:

```
Failover([
  "tcp://host1:61612",
  "tcp://host2:61612"
]);
```
