### ISSUE TITLE
wrong header sent for ACK/NACK using STOMP 1.2 and string as parameter

### ISSUE THREAD

**Issue by masi** [centraldesktop/php-stomp#5]
Both master and stomp-1.2 branch send "message-id" instead of "id" when ack() or nack() is called with a string as first parameter.

**Comment by treyhyde** [comment]
We were a little aggressive here but both id and message-id should be sent for connections of stomp versions > 1.1.   You are only seeing message-id?

**Comment by treyhyde** [comment]
I see what you're talking about now.
